import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';

import 'theme/solenne_theme.dart';
import 'core/network/api_client.dart';
import 'services/auth_service.dart';
import 'services/product_repository.dart';
import 'services/cart_repository.dart';
import 'services/wishlist_repository.dart';
import 'services/order_repository.dart';
import 'services/address_repository.dart';
import 'services/notification_repository.dart';
import 'services/inquiry_repository.dart';
import 'state/auth_state.dart';
import 'state/cart_state.dart';
import 'state/wishlist_state.dart';
import 'state/notification_state.dart';
import 'state/address_state.dart';
import 'ui/screens/root_shell.dart';

// import 'firebase_options.dart'; // generated by `flutterfire configure`

bool _firebaseInitialized = false;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Try to initialize Firebase for push notifications if needed, 
  // but it's no longer the main backend.
  try {
    await Firebase.initializeApp();
    _firebaseInitialized = true;
  } catch (e) {
    debugPrint('Firebase initialization optional: $e');
  }

  final apiClient = ApiClient();

  runApp(
    MultiProvider(
      providers: [
        Provider<ApiClient>.value(value: apiClient),
        Provider<AuthService>(create: (_) => AuthService(apiClient)),
        Provider<ProductRepository>(create: (_) => ProductRepository(apiClient)),
        Provider<CartRepository>(create: (_) => CartRepository(apiClient)),
        Provider<WishlistRepository>(create: (_) => WishlistRepository(apiClient)),
        Provider<OrderRepository>(create: (_) => OrderRepository(apiClient)),
        Provider<AddressRepository>(create: (_) => AddressRepository(apiClient)),
        Provider<NotificationRepository>(create: (_) => NotificationRepository(apiClient)),
        Provider<InquiryRepository>(create: (_) => InquiryRepository(apiClient)),
        ChangeNotifierProvider<AuthState>(
          create: (context) => AuthState(context.read<AuthService>()),
        ),
        ChangeNotifierProxyProvider<AuthState, CartState>(
          create: (context) => CartState(context.read<CartRepository>(), context.read<AuthState>()),
          update: (context, auth, previous) => previous ?? CartState(context.read<CartRepository>(), auth),
        ),
        ChangeNotifierProxyProvider<AuthState, WishlistState>(
          create: (context) => WishlistState(context.read<WishlistRepository>(), context.read<AuthState>()),
          update: (context, auth, previous) => previous ?? WishlistState(context.read<WishlistRepository>(), auth),
        ),
        ChangeNotifierProxyProvider<AuthState, NotificationState>(
          create: (context) => NotificationState(context.read<NotificationRepository>(), context.read<AuthState>()),
          update: (context, auth, previous) => previous ?? NotificationState(context.read<NotificationRepository>(), auth),
        ),
        ChangeNotifierProxyProvider<AuthState, AddressState>(
          create: (context) => AddressState(context.read<AddressRepository>(), context.read<AuthState>()),
          update: (context, auth, previous) => previous ?? AddressState(context.read<AddressRepository>(), auth),
        ),
      ],
      child: const SolenneApp(),
    ),
  );
}

class SolenneApp extends StatelessWidget {
  const SolenneApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SOLENNE',
      debugShowCheckedModeBanner: false,
      theme: SolenneTheme.light,
      home: const RootShell(),
    );
  }
}
