# Generated by Django 5.2.17 on 2026-09-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_contactmessage_is_read_contactmessage_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_read_by_user',
            field=models.BooleanField(default=True),
        ),
    ]
