# Generated by Django 5.2.14 on 2026-09-08 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_homesection_homesectioncategory_homesectionmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='mobile_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_sections_mobile', to='store.media'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='platform',
            field=models.CharField(choices=[('both', 'Both'), ('web', 'Web Only'), ('mobile', 'Mobile Only')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='homesection',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
