# Generated by Django 5.2.14 on 2026-09-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_productvariant_unique_product_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya_code', models.PositiveIntegerField(unique=True)),
                ('wilaya_name', models.CharField(max_length=100)),
                ('home_delivery_price', models.PositiveIntegerField()),
                ('stop_desk_price', models.PositiveIntegerField()),
                ('return_price', models.PositiveIntegerField(default=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['wilaya_code'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('home_delivery', 'Domicile'), ('stop_desk', 'Stop Desk')], default='home_delivery', max_length=20),
        ),
    ]
